### ISSUE TITLE
PHP notice on 7.1: A non well formed numeric value encountered

### ISSUE THREAD

**Issue by alsar** [phingofficial/phing#622]
When running Phing on PHP 7.1 I get a notice:
`PHP Notice:  A non well formed numeric value encountered in .composer/vendor/phing/phing/classes/phing/Phing.php on line 1636`

The problem seems to be here: https://github.com/phingofficial/phing/blob/2.15.2/classes/phing/Phing.php#L1636

And seems to be related to this RFC: https://wiki.php.net/rfc/invalid_strings_in_arithmetic

**Comment by mrook** [comment]
Already fixed in #620 - thanks for reporting!

**Comment by lastzero** [comment]
What release will this be in? It's now 3 months later and I still see this error when using the latest ~2.0 via composer.
